apiVersion: apps/v1
kind: Deployment
metadata:
  name: wimpserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wimpserver
  template:
    metadata:
      labels:
        app: wimpserver
    spec:
      containers:
        - name: wimpserver
          image: ghcr.io/agelito/wimp-server:latest
          env:
            - name: "ConnectionStrings__WimpDatabase"
              valueFrom:
                secretKeyRef:
                  name: wimp
                  key: db_connection_string
            - name: "JWT__Secret"
              valueFrom:
                secretKeyRef:
                  name: wimp
                  key: jwt_secret
            - name: "DefaultUser__Username"
              valueFrom:
                secretKeyRef:
                  name: wimp
                  key: default_username
            - name: "DefaultUser__Password"
              valueFrom:
                secretKeyRef:
                  name: wimp
                  key: default_password
          livenessProbe:
            httpGet:
              path: "/health"
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: "/health"
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: wimpserver-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: wimpserver
  ports:
    - name: wimpserver
      protocol: TCP
      port: 80
      targetPort: 80
    - name: wimpserver-ssl
      protocol: TCP
      port: 443
      targetPort: 443
