apiVersion: v1
kind: Service
metadata:
  name: mssql-wimp-nodeport-service
spec:
  type: NodePort
  selector:
    app: mssql-wimp
  ports:
    - name: mssql-wimp
      protocol: TCP
      port: 1433
      targetPort: 1433
