apiVersion: v1
kind: Service
metadata:
  name: wimpserver-nodeport-service
spec:
  type: NodePort
  selector:
    app: wimpserver
  ports:
    - name: wimpserver
      protocol: TCP
      port: 80
      targetPort: 80
    - name: wimpserver-ssl
      protocol: TCP
      port: 443
      targetPort: 443
